# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0
#Trying to get PypSA to solve ANYTHING -- this is with the mode bare bones of changes, just countries, snapshots, and cutout 



run:
  name: "" # use this to keep track of runs with different settings -- but if I change the name it doesn't run? 
  disable_progressbar: true

scenario:
  clusters:
  - 20
  opts:
  - ''

countries: ['DE']

snapshots:
  start: "2013-03-01"
  end: "2013-03-08"


electricity:
  co2limit_enable: true
  co2limit: 100.e+6

  extendable_carriers:
    Generator: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float, OCGT, CCGT]
    StorageUnit: [battery]
    Store: [H2] #probably want to give the model the option to add more than just h2 stores
    Link: [H2 pipeline] #probably want to give the model the option to add more than just h2 pipelines 

  renewable_carriers: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float]


atlite:
  default_cutout: de-2013-03-era5
  cutouts:
    de-2013-03-era5:
      module: era5
      x: [5., 16.]
      y: [47., 56.]
      time: ["2013-03-01", "2013-03-08"]

renewable:
  onwind:
    cutout: de-2013-03-era5
  offwind-ac:
    cutout: de-2013-03-era5
    max_depth: false
  offwind-dc:
    cutout: de-2013-03-era5
    max_depth: false
  offwind-float:
    cutout: de-2013-03-era5
    max_depth: false
    min_depth: false
  solar:
    cutout: de-2013-03-era5
  solar-hsat:
    cutout: de-2013-03-era5


clustering:
  exclude_carriers: ["OCGT", "offwind-ac", "coal"]
  temporal:
    resolution_elec: 3h

lines:
  dynamic_line_rating:
    activate: true
    cutout: de-2013-03-era5
    max_line_rating: 1.3


solving:
  solver:
    name: highs
    options: highs-simplex