# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0
#Trying to get PypSA to solve ANYTHING -- this is with the mode bare bones of changes, just countries, snapshots, and cutout 



run:
  name: "" # use this to keep track of runs with different settings -- but if I change the name it doesn't run? 
  disable_progressbar: false

scenario:
  clusters:
  - 39
  opts:
  - ''

countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'XK']

snapshots:
  start: "2022-01-01"
  end: "2023-01-01"
  inclusive: 'left'


electricity:
  co2limit_enable: false
  co2limit: 100.e+6

  extendable_carriers:
    Generator: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float, OCGT, CCGT]
    StorageUnit: [battery]
    Store: [battery, H2] #probably want to give the model the option to add more than just h2 stores
    Link: [H2 pipeline] #probably want to give the model the option to add more than just h2 pipelines 

  renewable_carriers: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float]


atlite:
  default_cutout: europe-2023-sarah3-era5
  cutouts:
    europe-2023-sarah3-era5:
      module: era5
      x: [-12., 42.]
      y: [33., 72.]
      dx: 0.3
      dy: 0.3
      time: ["2022", "2022"]

renewable:
  onwind:
    cutout: europe-2023-sarah3-era5
  offwind-ac:
    cutout: europe-2023-sarah3-era5
    max_depth: false
  offwind-dc:
    cutout: europe-2023-sarah3-era5
    max_depth: false
  offwind-float:
    cutout: europe-2023-sarah3-era5
    max_depth: false
    min_depth: false
  solar:
    cutout: europe-2023-sarah3-era5
  solar-hsat:
    cutout: europe-2023-sarah3-era5
  solar thermal: 
    cutout: europe-2023-sarah3-era5


clustering:
  exclude_carriers: ["OCGT", "offwind-ac", "coal"]
  temporal:
    resolution_elec: false #3h according to the configuration file, this options should only be used with electric networks, not sector coupled networks 
    resolution_sector: 6H

sector:
  gas_network: true
  H2_retrofit: true
  biomass: false
  industry: false
  agriculture: false
  fossil_fuels: true
  shipping: false
  aviation: false
  heating: true


lines:
  dynamic_line_rating:
    activate: false
    cutout: europe-2019-sarah3-era5
    max_line_rating: 1.3


solving:
  solver:
    name: gurobi
    options: gurobi-default
