# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

private:
  keys:
    entsoe_api: 53f9250b-91d3-4d15-af4f-c0b8b1f155e2

run:
  name: "" # use this to keep track of runs with different settings -- but if I change the name it doesn't run? 
  disable_progressbar: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight:  myopic

scenario:
  clusters:
  - 39
  sector_opts:
  - ''
  planning_horizons:
  - 2020
  #- 2025
  - 2030
  #- 2035
  - 2040
  #- 2045
  - 2050

countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'XK']

snapshots:
  start: "2019-01-01"
  end: "2020-01-01"
  inclusive: 'left'

co2_budget:
  2020: 0.720 #average emissions of 2019 to 2021 relative to 1990, CO2 excl LULUCF, EEA data, European Environment Agency. (2023a). Annual European Union greenhouse gas inventory 1990–2021 and inventory report 2023 - CRF Table. https://unfccc.int/documents/627830
    #2025: 0.648 # With additional measures (WAM) projection, CO2 excl LULUCF, European Environment Agency. (2023e). Member States’ greenhouse gas (GHG) emission projections 2023. https://www.eea.europa.eu/en/datahub/datahubitem-view/4b8d94a4-aed7-4e67-a54c-0623a50f48e8
  2030: 0.450 # 55% reduction by 2030 (Ff55)
    #2035: 0.250
  2040: 0.100 # 90% by 2040
    #2045: 0.050
  2050: 0.050 

transmission_limit: copt 


electricity:
  co2limit_enable: false
  co2limit: 100.e+6

  extendable_carriers:
    Generator: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float, OCGT, CCGT, coal, lignite, geothermal, biomass, oil] #can extend any generator..., except nuclear
    StorageUnit: [battery]
    Store: [battery, H2] #[H2], but I want to give the model an option to use batteries for more long term storage
    Link: [H2 pipeline] #Adds extendable links (H2 pipelines only) at every connection where there are lines or HVDC links without capacity limits and with zero initial capacity. Hydrogen pipelines require hydrogen storage to be modelled as Store

  renewable_carriers: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float, hydro]
  conventional_carriers: [nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass]
  powerplants_filter: (DateOut >= 2020 or DateOut != DateOut)

  estimate_renewable_capacities:
    enable: false #true, "Activate routine to estimate renewable capacities in rule add_electricity. This option should not be used in combination with pathway planning foresight: myopic or foresight: perfect as renewable capacities are added differently in add_existing_baseyear"
    from_opsd: true
    year: 2020
    expansion_limit: false
    technology_mapping:
      Offshore: [offwind-ac, offwind-dc, offwind-float]
      Onshore: [onwind]
      PV: [solar]



atlite:
  cutout_directory: cutouts
  default_cutout: europe-2019-sarah3-era5
  nprocesses: 4 
  cutouts:
    europe-2019-sarah3-era5:
      module: [sarah, era5] # in priority order
      x: [-12., 42.]
      y: [33., 72.]
      dx: 0.3
      dy: 0.3
      time: ["2019", "2019"]

renewable:
  onwind:
    cutout: europe-2019-sarah3-era5
  offwind-ac:
    cutout: europe-2019-sarah3-era5
  offwind-dc:
    cutout: europe-2019-sarah3-era5
  offwind-float:
    cutout: europe-2019-sarah3-era5
  solar:
    cutout: europe-2019-sarah3-era5
  solar-hsat:
    cutout: europe-2019-sarah3-era5
  hydro:
    cutout: europe-2019-sarah3-era5

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#conventional
conventional:
  unit_commitment: false
  dynamic_fuel_price: true #was false, but want to see if a monthly fuel price improves validation
  nuclear:
    p_max_pu: "data/nuclear_p_max_pu.csv" # float of file name



# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#solar-thermal
solar_thermal:
  clearsky_model: simple  # should be "simple" or "enhanced"?
  orientation:
    slope: 45.
    azimuth: 180.
  cutout: europe-2019-sarah3-era5 #changed from default in default file

limit_capacity_by_country : false #false means that the limits applied to all of Europe, true means the structure has to mimic pypsa DE and apply to the whole country
## CUSTOM CONSTRAINT of Carrier Specific Capcity Growth (Modelled AFTER FUNCTION IN PYPSA DE)




# regulate what components with which carriers are kept from PyPSA-Eur;
# some technologies are removed because they are implemented differently
# (e.g. battery or H2 storage) or have different year-dependent costs
# in PyPSA-Eur-Sec
pypsa_eur: #I think I need to add in conventional generators and buses into the file here, because right now the electric component carriers 
#are only the carriers that are given here, I think what is happening is that pypsa-eur when merging with the sector additions gets trimmed, and it's pruning too much

  Bus:
  - AC  
  - gas
  - lignite
  - coal 
  #- import export tracker
  - oil
  #- biomass 
  Link:
  - DC
  - OCGT
  - CCGT
  - lignite
  - biomass
  - oil
  - coal 
  Generator:
  - onwind
  - offwind-ac
  - offwind-dc
  - offwind-float
  - solar-hsat
  - solar
  - ror
  - nuclear
  #- biomass
  #- coal
  #- OCGT
  #- CCGT
  #- lignite
  #- solid biomass #because this is included in sector, does it need to be included here? #including this didn't make solid biomass have a carbon value, also it's still included in links, my guess
  - geothermal 
  #- oil #once removed oil because agriculture and industry were not solving as sectors, kept saying that the spatial.nodes.oil bus wasn't created in scripts/prepare_sector_network.py, so maybe it's because oil should be considered a carrier not a generator
  #led to biomass being used everywhere??? [Friday April 25], and a huge huge overestimation of generation 
  StorageUnit:
  - PHS
  - hydro
  Store: []


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#existing-capacities
existing_capacities:
  grouping_years_power: [1920, 1950, 1955, 1960, 1965, 1970, 1975, 1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2019, 2020, 2022, 2025, 2027, 2030]
  grouping_years_heat: [1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2019] # heat grouping years >= baseyear will be ignored
  threshold_capacity: 10
  default_heating_lifetime: 20
  conventional_carriers:
  - lignite
  - coal
  - oil
  - uranium
  - gas

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#transmission_projects
transmission_projects:
  enable: true
  include:
    tyndp2020: true
    nep: true
    manual: true
  skip:
  - upgraded_lines
  - upgraded_links
  status:
  - under_construction
  - in_permitting
  - confirmed
    #- planned_not_yet_permitted
    #- under_consideration
  new_link_capacity: zero #keep or zero #I don't know what to do with this one really...



sector:
  transport: true
  heating: true
  biomass: true
  industry: true #this doesn't work for lack of fischer-tropsch buses #that is solved if you put oil in bus: and link: under pypsa_eur
  agriculture: true #doesn't work for lack of EU agricultural machinery oil bus #this is solved if you putp oil in bus: and link" under pypsa_eur 
  fossil_fuels: true
  shipping: true
  aviation: true
  regional_oil_demand: true #because both industry and agriculture wouldn't solve because it couldn't find the EU oil bus, does this help? NO this made it worse
  
  conventional_generation:
    OCGT: gas
    lignite: lignite 
    coal: coal 
    CCGT: gas


  #BEV related flags 
  bev_dsm: false  #see bev_dsm availability 
  v2g: false  #set v2g availability
  bev_dsm_restriction_value: 0.75
  bev_dsm_restriction_time: 7
  bev_energy: 0.05
  bev_charge_efficiency: 0.9
  bev_dsm_availability: 0.0 #DSM availability changed in each scenario
  bev_charge_rate: 0.011
  bev_avail_max: 0.95
  bev_avail_mean: 0.8

  land_transport_fuel_cell_share:
    2020: 0
    2025: 0
    2030: 0
    2035: 0
    2040: 0
    2045: 0
    2050: 0
  land_transport_electric_share:
    2020: 0
    2025: 0.15
    2030: 0.3
    2035: 0.45
    2040: 0.7
    2045: 0.85
    2050: 1
  land_transport_ice_share:
    2020: 1
    2025: 0.85
    2030: 0.7
    2035: 0.55
    2040: 0.3
    2045: 0.15
    2050: 0

  shipping_hydrogen_share:
    2020: 0
    2025: 0
    2030: 0
    2035: 0
    2040: 0
    2045: 0
    2050: 0
  shipping_methanol_share:
    2020: 0
    2025: 0.15
    2030: 0.3
    2035: 0.5
    2040: 0.7
    2045: 0.85
    2050: 1
  shipping_oil_share:
    2020: 1
    2025: 0.85
    2030: 0.7
    2035: 0.5
    2040: 0.3
    2045: 0.15
    2050: 0

### Heating related flags 
  tes: true
  additional_hot_water_tanks: false #for adding additional hot water tanks
  number_households: 100000000  #should match eurostat eventually, now just 1 million (should probably be 100 million to be half Eurostat)
  water_tank_standing_loss: 0.02 # see Small scale hot water tank https://ens.dk/en/our-services/projections-and-models/technology-data/technology-data-energy-storage
  water_tank_max_hours: 12  # Decision based on Lizana et al. 2023 Fig 12 b1 
  boilers: true #gas heating, yeah that's what is happening now
  resistive_heaters: true #resistive heating using electricity, yes
  boiers: true 
  oil_boilers: false
  biomass_boilers: true 
  solar_thermal: true

## carbon related flags 
  methanation: true #methanation here because it uses CO2 as an input, but it also uses hydrogen 
  coal_cc: false #coal plants are most polluting plant in Europe, so taking away carbon capture? https://www.eea.europa.eu/highlights/coal-fired-power-plants-remain 
  dac: true #true in BAU scenario because national plans assume use of dac.
  co2_vent: false
  central_heat_vent: true
  allam_cycle_gas: false

  regional_co2_sequestration_potential:
    enable: true #true in Bobby's work and in the Hdyrogen and CO2 networks files
    attribute:
    - conservative estimate Mt #this is the only one Lukas had enabled, Bobby's work also included the Gas and OIl
    #- conservative estimate GAS Mt
    #- conservative estimate OIL Mt
    #- conservative estimate aquifer Mt
    include_onshore: false
    min_size: 3
    max_size: 25
    years_of_storage: 25
  co2_sequestration_potential: #different for BAU scenario
    2020: 0
    2025: 0
    2030: 0 #50
    2035: 0 #100
    2045: 0 #200
    2040: 0 #200
    2050: 0 #200
  co2_sequestration_cost: 10
  co2_sequestration_lifetime: 50
  co2_spatial: true
  co2_network: false
  co2_network_cost_factor: 1
  cc_fraction: 0.9


##hydrogen related flags #all turned on, just some limited in Scenarios 3
  hydrogen_underground_storage: true #true, June 23, trying to eliminate hydrogen network 
  hydrogen_fuel_cell: true 
  hydrogen_turbine: false
  SMR: true
  SMR_cc: true 
  H2_network: true
  gas_network: true #add existing gas network 
  H2_retrofit: true #for simplified version, don't need hydrogen retrofit, but the model can build hydrogen completely from new 
  bioH2: true #but should be true for future hydrogen runs


  methanol: 
    regional_methanol_demand: false
    methanol_reforming: false
    methanol_reforming_cc: false
    methanol_to_kerosene: false
    methanol_to_power:
      ccgt: false
      ccgt_cc: false
      ocgt: false
      allam: false
    biomass_to_methanol: false
    biomass_to_methanol_cc: false

  #Use of the snthetic fuels processes for waste heat 
  ammonia: false
  min_part_load_fischer_tropsch: 0.5
  min_part_load_methanolisation: 0.3
  min_part_load_methanation: 0.3
  use_fischer_tropsch_waste_heat: 0.25
  use_haber_bosch_waste_heat: 0.25
  use_methanolisation_waste_heat: 0.25
  use_methanation_waste_heat: 0.25
  use_fuel_cell_waste_heat: 0.25
  use_electrolysis_waste_heat: 0.25

  #The rest of the defaults I agree with 
  chp:
    enable: true
    fuel:
    - solid biomass # For solid biomass, CHP with and without CC are added
    - gas # For all other fuels the same techno economic data from gas CHP is taken
  electricity_distribution_grid: true
 
## Biomass flags (except bio_to_h2, which is in H2)
biomass_to_liquid: false
biomass_to_liquid_cc: false
electrobiofuels: false
biosng: false
biosng_cc: false
municipal_solid_waste: false

biomass_spatial: true #default = false, adds options for resolving biomass demand regionally
biomass_transport: false #default = false, adds option for transporting solid biomass between nodes


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#biomass
biomass:
  year: 2030
  scenario: ENS_Med
  classes:
    solid biomass:
    - Agricultural waste
    - Fuelwood residues
    - Secondary Forestry residues - woodchips
    - Sawdust
    - Residues from landscape care
    not included:
    - Sugar from sugar beet
    - Rape seed
    - "Sunflower, soya seed "
    - Bioethanol barley, wheat, grain maize, oats, other cereals and rye
    - Miscanthus, switchgrass, RCG
    - Willow
    - Poplar
    - FuelwoodRW
    - C&P_RW
    biogas:
    - Manure solid, liquid
    - Sludge
    municipal solid waste:
    - Municipal waste
  share_unsustainable_use_retained:
    2020: 1
    2025: 0.66
    2030: 0.33
    2035: 0
    2040: 0
    2045: 0
    2050: 0
  share_sustainable_potential_available:
    2020: 0
    2025: 0.33
    2030: 0.66
    2035: 1
    2040: 1
    2045: 1
    2050: 1


enhanced_geothermal:
  enable: false
  flexible: true
  max_hours: 240
  max_boost: 0.25
  var_cf: true
  sustainability_factor: 0.0025
solid_biomass_import:
  enable: false
  price: 54 #EUR/MWh
  max_amount: 1390 # TWh
  upstream_emissions_factor: .1 #share of solid biomass CO2 emissions at full combustion

lines:
  dynamic_line_rating:
    activate: false
    cutout: europe-2019-sarah3-era5
    max_line_rating: 1.3


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#costs
costs:
  year: 2030
  version: v0.10.1
  social_discountrate: 0.02 #should the social discount rate be 2 percent #lower social discount rate is paces more weight on future costs and therefore might make more decarbonized system faster? 
  fill_values:
    FOM: 0
    VOM: 0
    efficiency: 1
    fuel: 0
    investment: 0
    lifetime: 25
    "CO2 intensity": 0 #global carbon constraint uses co2 atmosphere store, co2 intensity defines the efficiency of links from original stores to buses.
    "discount rate": 0.07 #does this overadd the social_discount rate above, ? 
  overwrites: {} 
  capital_cost: ##AHHHH THESE PROBABLY SHOULD BE PER MW NOT JUST THE TOTALS #added because there was geothermal produced in Italy even though there was a capital cost that should have been included. 
    geothermal: 3241320 #added overnight costs from here https://iea.blob.core.windows.net/assets/ae17da3d-e8a5-4163-a3ec-2e6fb0b5677d/Projected-Costs-of-Generating-Electricity-2020.pdf   #added because there was geothermal produced in Italy even though there was a capital cost that should have been included. 
    #H2: 1000000.00 #did not work, added to try and push down electrolysis usage
  marginal_cost:
    solar: 0.01
    onwind: 0.015
    offwind: 0.015
    hydro: 0.
    electrolysis: 0.0
    fuel cell: 0.
    battery: 0.
    battery inverter: 0.
  emission_prices:
    enable: true
    co2: 0.0 #25 EUR/t CO2 
    co2_monthly_prices: false


clustering:
  aggregation_strategies:
    generators:
      committable: any
      ramp_limit_up: max
      ramp_limit_down: max
  temporal:
    resolution_elec: false #should only be used if the network is purely electric, otherwise use resolution_sector for sector-coupled network 
    resolution_sector: 6H #should be 3 hours for best study temporal resolution


solving:
  options:
    curtailment_mode: false

  #agg_p_nom_limits:
  #  agg_offwind: false
  #  include_existing: false
  #  file: data/agg_p_nom_minmax.csv



  solver:
    name: gurobi
    options: gurobi-default
